version: '3.9'

services:
  server:
    build:
      context: . # üëà –ö–æ–Ω—Ç–µ–∫—Å—Ç —Å–±–æ—Ä–∫–∏ ‚Äî —Ç–µ–∫—É—â–∞—è –ø–∞–ø–∫–∞ "app"
      dockerfile: ./server/Dockerfile # üëà Dockerfile –≤–Ω—É—Ç—Ä–∏ "server"
    container_name: mern-server
    restart: always
    ports:
      - '80:3005'
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://user:mongopass@mongo:27017/testdb

  mongo:
    image: mongo:7
    container_name: mern-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: testdb
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: mongopass,
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
